language: ruby
rvm:
  - "2.0.0"
before_install:
  - git submodule update --init --recursive
notifications:
  email:
    recipients:
      - "shaune@princeton.edu"
      - "jstroop@princeton.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"